version: '3.8'

services:
  api:
    build: .
    container_name: housing_api
    working_dir: /app/src
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  frontend:
    build: .
    container_name: housing_frontend
    working_dir: /app/src
    command: streamlit run app.py --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - api 
    